# Site Info
title:              "Qure.ai Tech Blog"
name:               "Qure.ai"
email:              "prashant.warier@qure.ai"
description:        "Technology notes from pioneers at Qure.ai"
google_verify:      _2WtneGeJF7CpXIMHzlp6Ott3WB-AKSriC5U9E6o8UY # Put your Google Verification here
google_analytics:   UA-81296422-1 # Put your Google Analytics code
twitter_username: qure_ai
logo: "/assets/greyQ.png"

# Site Settings
baseurl:            ""
url:                "https://blog.qure.ai"
author:             "Qure.ai Tech Team"
permalink:          /notes/:title # Post permalink
timezone:           Asia/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Pagination
paginate: 4
paginate_path: "page/:num"
plugins: [jekyll-paginate]

# Site Build
highlighter:        rouge
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

# social icons and sharing options
social:
  - icon: globe
    url:  http://qure.ai
    desc: Go to website
    share_url:
    share_title:
    share_link:

  - icon:	twitter
    url:	https://twitter.com/qure_ai
    desc: Follow on twitter
    share_url: https://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/qureai
    desc:	Fork on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
  
# default values
defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
